{
 "title": "FastAPI Monitoring",
 "tags": [
  "fastapi",
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}