"""Data models for normalized findings and analysis output."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(slots=True)
class Finding:
    """Represents a normalized scan finding from a security scanner."""

    source_tool: str
    file_name: str
    issue_type: str
    severity: str
    message: str
    line_number: int | None = None
    raw: dict[str, Any] | None = None


@dataclass(slots=True)
class AnalysisResult:
    """Structured response generated by the agent for a finding."""

    issue: str
    severity: str
    risk: str
    fix: str
    confidence: float

    def __post_init__(self) -> None:
        """Validates field values after initialization."""
        if not self.issue:
            raise ValueError("issue must not be empty")
        if self.severity not in {"LOW", "MEDIUM", "HIGH"}:
            raise ValueError("severity must be LOW, MEDIUM, or HIGH")
        if not self.risk:
            raise ValueError("risk must not be empty")
        if not self.fix:
            raise ValueError("fix must not be empty")
        if not 0.0 <= float(self.confidence) <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")

    @classmethod
    def model_validate(cls, payload: dict[str, Any]) -> "AnalysisResult":
        """Creates an analysis result from a dictionary payload."""
        return cls(
            issue=str(payload.get("issue", "")).strip(),
            severity=str(payload.get("severity", "")).strip().upper(),
            risk=str(payload.get("risk", "")).strip(),
            fix=str(payload.get("fix", "")).strip(),
            confidence=float(payload.get("confidence", 0.0)),
        )

    def model_dump(self) -> dict[str, Any]:
        """Returns a serializable dictionary for CLI output."""
        return asdict(self)


@dataclass(slots=True)
class CommentTarget:
    """Represents a GitHub pull request comment target."""

    owner: str
    repo: str
    pull_number: int


def finding_to_dict(finding: Finding) -> dict[str, Any]:
    """Converts a finding to a serializable dictionary."""
    return asdict(finding)
